# Generated by Django 3.0.4 on 2020-04-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movieranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieranking',
            old_name='rank',
            new_name='score',
        ),
    ]
