# Generated by Django 3.0.4 on 2020-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200413_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
