# Generated by Django 3.0.4 on 2020-04-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('movies', '0004_movie_seen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieRanking',
            new_name='MovieScore',
        ),
    ]
