# Generated by Django 3.0.4 on 2020-04-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200413_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviescore',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='moviescore',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
